name = "artsbyas-website"
main = "dist/_worker.js"
compatibility_date = "2026-08-17"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "artsbyas-db"
database_id = "8456ac9b-36ca-4427-bee6-e0ebfed07dfe"

